name: Docker Image CI

on:
  push:
    branches: [ "mains" ]
env:
  AWS_REGION: ap-northeast-2   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: koko # set this to your Amazon ECR repository name
permissions:
  id-token: write   # This is required for requesting the JWT through OIDC
  contents: read  

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
          
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: "ROLE ARN FROM TERRAFORM OUTPUT"
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./src/terraform
      id: init
      run: terraform init
        
    - name: Terraform Plan
      id: plan
      working-directory: ./src/terraform
      run: |
        echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
        terraform plan -no-color >> $GITHUB_STEP_SUMMARY
    
    

